repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.5
    hooks:
    -   id: clang-format
        exclude: '^components/btstack|^components/arduino|^components/cmd_nvs*|^components/cmd_system*'
